import type { GalleryImage, CategoryMeta } from './types';

export const CATEGORIES: CategoryMeta[] = [
  { id: 'all', label: 'All', color: 'mauve' },
  { id: 'treatments', label: 'Treatments', color: 'mauve' },
  { id: 'products', label: 'Products', color: 'sage' },
  { id: 'ambiance', label: 'Our Space', color: 'deep' },
  { id: 'results', label: 'Results', color: 'mauve' },
];

const CLD = 'https://res.cloudinary.com/dhmqhless/image/upload/q_auto:good,f_auto';

export const GALLERY_IMAGES: GalleryImage[] = [
  // ── Treatments ─────────────────────────────────────────────────────
  {
    id: 'g-01',
    src: `${CLD}/v1778092806/skin-ig3_og3xnh.jpg`,
    alt: 'Signature facial treatment',
    category: 'treatments',
    title: 'Signature Facial',
    description: 'Our signature deep-cleansing and hydrating facial',
    span: 'large',
  },
  {
    id: 'g-02',
    src: `${CLD}/v1778093141/skin-ig4_ihjvl0.jpg`,
    alt: 'Professional skin treatment in progress',
    category: 'treatments',
    title: 'Skin Therapy',
    description: 'Advanced treatment calibrated to your skin signature',
    span: 'normal',
  },
  {
    id: 'g-03',
    src: `${CLD}/v1778092844/skin-ig1_ksvzcl.jpg`,
    alt: 'Spa therapy session',
    category: 'treatments',
    title: 'Spa Therapy',
    description: 'Immersive body and skin restoration ritual',
    span: 'normal',
  },
  {
    id: 'g-04',
    src: `${CLD}/v1778092844/skin-ig2_w7tvnk.jpg`,
    alt: 'Premium skincare treatment close-up',
    category: 'treatments',
    title: 'Premium Care',
    description: 'Expert-guided ritual for visible transformation',
    span: 'wide',
  },

  // ── Products ────────────────────────────────────────────────────────
  {
    id: 'g-05',
    src: `${CLD}/v1778028814/skin-essential-plus/homepage/hero/home-page-hero4.jpg`,
    alt: 'Complete skincare product collection',
    category: 'products',
    title: 'Skincare Collection',
    description: 'Premium formulations curated for every skin type',
    span: 'wide',
  },
  {
    id: 'g-06',
    src: `${CLD}/v1778093837/skin-ig5_qfrkfe.jpg`,
    alt: 'Lash artistry at Skin Essential Plus',
    category: 'products',
    title: 'Lash Artistry',
    description: 'Bespoke lash extensions and precision styling',
    span: 'normal',
  },
  {
    id: 'g-07',
    src: `${CLD}/v1778181113/skin-ig6_l62kds.jpg`,
    alt: 'Daily skincare ritual products',
    category: 'products',
    title: 'Daily Ritual',
    description: 'Science-backed morning and evening routine',
    span: 'tall',
  },
  {
    id: 'g-08',
    src: `${CLD}/v1778028811/skin-essential-plus/homepage/hero/home-page-hero2.jpg`,
    alt: 'Treatment essentials on display',
    category: 'products',
    title: 'Treatment Essentials',
    description: 'Clinical-grade formulations for visible results',
    span: 'normal',
  },

  // ── Ambiance ────────────────────────────────────────────────────────
  {
    id: 'g-09',
    src: `${CLD}/v1778795958/sanctuary_abo2g1.jpg`,
    alt: 'Skin Essential Plus sanctuary interior',
    category: 'ambiance',
    title: 'Our Sanctuary',
    description: 'A space designed for healing and transformation',
    span: 'large',
  },
  {
    id: 'g-10',
    src: `${CLD}/v1778092806/skin-ig3_og3xnh.jpg`,
    alt: 'Treatment studio atmosphere',
    category: 'ambiance',
    title: 'Treatment Studio',
    description: 'Where expertise meets serenity',
    span: 'normal',
  },
  {
    id: 'g-11',
    src: `${CLD}/v1778092844/skin-ig1_ksvzcl.jpg`,
    alt: 'Serene spa environment',
    category: 'ambiance',
    title: 'Serenity Space',
    description: 'A calming haven for your rituals',
    span: 'normal',
  },
  {
    id: 'g-12',
    src: `${CLD}/v1778093141/skin-ig4_ihjvl0.jpg`,
    alt: 'Pre-treatment relaxation lounge',
    category: 'ambiance',
    title: 'Relaxation Lounge',
    description: 'Pre and post-treatment comfort',
    span: 'wide',
  },

  // ── Results ─────────────────────────────────────────────────────────
  {
    id: 'g-r1',
    src: `${CLD}/v1778795958/beforeandafter1_qyjabc.jpg`,
    alt: 'Visible skin transformation before and after',
    category: 'results',
    title: 'Before & After',
    description: 'Real client result from our signature skin treatment',
    span: 'normal',
  },
  {
    id: 'g-r2',
    src: `${CLD}/v1778795957/beforeandafter_xbmack.jpg`,
    alt: 'Skin transformation result',
    category: 'results',
    title: 'Visible Transformation',
    description: 'Real client result from our advanced skincare protocol',
    span: 'normal',
  },
  {
    id: 'g-r3',
    src: `${CLD}/v1778613290/before-eye_xnmfcb.jpg`,
    alt: 'Eye treatment before result',
    category: 'results',
    title: 'Eye Transformation',
    description: 'Before our signature eye lash treatment',
    span: 'tall',
  },
  {
    id: 'g-r4',
    src: `${CLD}/v1778613290/after-eye_f8azs4.jpg`,
    alt: 'Beautiful eye lash result after treatment',
    category: 'results',
    title: 'Radiant Eyes',
    description: 'After our premium lash treatment',
    span: 'normal',
  },
  {
    id: 'g-r5',
    src: `${CLD}/v1778093837/skin-ig5_qfrkfe.jpg`,
    alt: 'Lash enhancement result',
    category: 'results',
    title: 'Lash Enhancement',
    description: 'Precision lash work by our expert artists',
    span: 'wide',
  },
];
