import type { GalleryImage, CategoryMeta } from './types';

export const CATEGORIES: CategoryMeta[] = [
  { id: 'all', label: 'All', color: 'mauve' },
  { id: 'treatments', label: 'Treatments', color: 'mauve' },
  { id: 'products', label: 'Products', color: 'sage' },
  { id: 'ambiance', label: 'Our Space', color: 'deep' },
  { id: 'results', label: 'Results', color: 'mauve' },
];

export const GALLERY_IMAGES: GalleryImage[] = [
  // Treatments
  {
    id: 'g-01',
    src: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1200&q=90&auto=format&fit=crop',
    alt: 'Facial treatment session',
    category: 'treatments',
    title: 'Signature Facial',
    description: 'Our signature 90-minute deep cleansing and hydrating facial',
    span: 'large',
  },
  {
    id: 'g-02',
    src: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&q=90&auto=format&fit=crop',
    alt: 'Microneedling treatment',
    category: 'treatments',
    title: 'Microneedling Session',
    description: 'Collagen induction therapy for skin rejuvenation',
    span: 'normal',
  },
  {
    id: 'g-03',
    src: 'https://images.unsplash.com/photo-1559599238-2c0925a575dd?w=1200&q=90&auto=format&fit=crop',
    alt: 'LED light therapy',
    category: 'treatments',
    title: 'LED Light Therapy',
    description: 'Red and blue light for anti-aging and acne treatment',
    span: 'normal',
  },
  {
    id: 'g-04',
    src: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=1200&q=90&auto=format&fit=crop',
    alt: 'Gua sha massage',
    category: 'treatments',
    title: 'Gua Sha Sculpting',
    description: 'Traditional facial sculpting and lymphatic drainage',
    span: 'wide',
  },

  // Products
  {
    id: 'g-05',
    src: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1200&q=90&auto=format&fit=crop',
    alt: 'Serum collection',
    category: 'products',
    title: 'The Serum Collection',
    description: 'Our complete range of targeted treatment serums',
    span: 'wide',
  },
  {
    id: 'g-06',
    src: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=1200&q=90&auto=format&fit=crop',
    alt: 'Vitamin C serum',
    category: 'products',
    title: 'Radiance Vitamin C',
    description: 'Brightening antioxidant serum',
    span: 'normal',
  },
  {
    id: 'g-07',
    src: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=1200&q=90&auto=format&fit=crop',
    alt: 'Skincare flatlay',
    category: 'products',
    title: 'Daily Ritual',
    description: 'Complete morning and evening routine',
    span: 'tall',
  },
  {
    id: 'g-08',
    src: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=1200&q=90&auto=format&fit=crop',
    alt: 'Moisturizer texture',
    category: 'products',
    title: 'Velvet Day Cream',
    description: 'Lightweight hydration with SPF 30',
    span: 'normal',
  },

  // Ambiance
  {
    id: 'g-09',
    src: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&q=90&auto=format&fit=crop',
    alt: 'Treatment room',
    category: 'ambiance',
    title: 'Serenity Suite',
    description: 'Our private treatment rooms',
    span: 'large',
  },
  {
    id: 'g-10',
    src: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=1200&q=90&auto=format&fit=crop',
    alt: 'Reception area',
    category: 'ambiance',
    title: 'Reception Lounge',
    description: 'Where your journey begins',
    span: 'normal',
  },
  {
    id: 'g-11',
    src: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=1200&q=90&auto=format&fit=crop',
    alt: 'Spa products display',
    category: 'ambiance',
    title: 'Product Sanctuary',
    description: 'Our curated retail space',
    span: 'normal',
  },
  {
    id: 'g-12',
    src: 'https://images.unsplash.com/photo-1610558751610-0db914e3e2e5?w=1200&q=90&auto=format&fit=crop',
    alt: 'Relaxation area',
    category: 'ambiance',
    title: 'Quiet Lounge',
    description: 'Pre and post-treatment relaxation',
    span: 'wide',
  },

  // Results
  {
    id: 'g-r1',
    src: 'https://res.cloudinary.com/dhmqhless/image/upload/v1778795958/beforeandafter1_qyjabc.jpg',
    alt: 'Skin transformation result',
    category: 'results',
    title: 'Before & After',
    description: 'Real client result from our signature skin treatment',
    span: 'normal',
  },
  {
    id: 'g-r2',
    src: 'https://res.cloudinary.com/dhmqhless/image/upload/v1778795957/beforeandafter_xbmack.jpg',
    alt: 'Skin transformation result',
    category: 'results',
    title: 'Visible Transformation',
    description: 'Real client result from our advanced skincare protocol',
    span: 'normal',
  },
  {
    id: 'g-13',
    src: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&q=90&auto=format&fit=crop',
    alt: 'Glowing skin close-up',
    category: 'results',
    title: 'Radiant Glow',
    description: 'After 8 weeks of our brightening protocol',
    span: 'tall',
  },
  {
    id: 'g-14',
    src: 'https://images.unsplash.com/photo-1602192509154-0b900ee1f851?w=1200&q=90&auto=format&fit=crop',
    alt: 'Clear skin transformation',
    category: 'results',
    title: 'Clear & Balanced',
    description: 'Post acne treatment program',
    span: 'normal',
  },
  {
    id: 'g-15',
    src: 'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?w=1200&q=90&auto=format&fit=crop',
    alt: 'Hydrated skin',
    category: 'results',
    title: 'Deep Hydration',
    description: 'After our intensive moisture therapy',
    span: 'normal',
  },
  {
    id: 'g-16',
    src: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=1200&q=90&auto=format&fit=crop',
    alt: 'Smooth skin texture',
    category: 'results',
    title: 'Refined Texture',
    description: 'Results from retinaldehyde treatment',
    span: 'wide',
  },
];